package AtomM.GUI;

import java.io.File;
import javax.swing.JFileChooser;

public class FConverter extends javax.swing.JFrame {

    public FConverter() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paGeneral = new javax.swing.JPanel();
        laPath = new javax.swing.JLabel();
        tfPath = new javax.swing.JTextField();
        buPath = new javax.swing.JButton();
        laPref = new javax.swing.JLabel();
        tfPref = new javax.swing.JTextField();
        chPassword = new javax.swing.JCheckBox();
        tfPassword = new javax.swing.JTextField();
        laVersion = new javax.swing.JLabel();
        cbVersion = new javax.swing.JComboBox();
        paSql = new javax.swing.JPanel();
        chParseAll = new javax.swing.JCheckBox();
        chParseUsers = new javax.swing.JCheckBox();
        chParseForum = new javax.swing.JCheckBox();
        chParseLoads = new javax.swing.JCheckBox();
        chParsePubl = new javax.swing.JCheckBox();
        chParseNews = new javax.swing.JCheckBox();
        chParseComments = new javax.swing.JCheckBox();
        chEmpty = new javax.swing.JCheckBox();
        chSplit = new javax.swing.JCheckBox();
        paParsing = new javax.swing.JPanel();
        chWebAvatars = new javax.swing.JCheckBox();
        chImage = new javax.swing.JCheckBox();
        chSmile = new javax.swing.JCheckBox();
        chLinks = new javax.swing.JCheckBox();
        laSiteOld = new javax.swing.JLabel();
        tfSiteOld = new javax.swing.JTextField();
        laSiteNew = new javax.swing.JLabel();
        tfSiteNew = new javax.swing.JTextField();
        laPost = new javax.swing.JLabel();
        spPost = new javax.swing.JSpinner();
        chFix = new javax.swing.JCheckBox();
        buStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JConverterGUI 0.5");
        setLocationByPlatform(true);
        setName("ConverterForm"); // NOI18N

        paGeneral.setBorder(javax.swing.BorderFactory.createTitledBorder("Общие настройки"));

        laPath.setText("Путь к бекапу Ucoz");

        buPath.setText("jButton1");
        buPath.setMaximumSize(new java.awt.Dimension(19, 19));
        buPath.setMinimumSize(new java.awt.Dimension(19, 19));
        buPath.setPreferredSize(new java.awt.Dimension(19, 19));
        buPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buPathActionPerformed(evt);
            }
        });

        laPref.setText("Префикс для таблиц");

        chPassword.setText("Сбросить пароль администратора");
        chPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chPasswordActionPerformed(evt);
            }
        });

        tfPassword.setEnabled(false);

        laVersion.setText("Версия CMS");

        cbVersion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fapos 0.9.93", "Fapos 1.0/1.1", "Fapos 1.1.8 beta", "Fapos 1.1.9", "Fapos 1.2 beta", "Fapos 1.3 RC", "Fapos 2.1 RC7", "Fapos 2.2 RC1", "Fapos 2.4 RC5", "AtomX 2.5 RC1 / AtomM 3", "AtomM 4", "AtomM 5" }));
        cbVersion.setSelectedIndex(11);

        javax.swing.GroupLayout paGeneralLayout = new javax.swing.GroupLayout(paGeneral);
        paGeneral.setLayout(paGeneralLayout);
        paGeneralLayout.setHorizontalGroup(
            paGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paGeneralLayout.createSequentialGroup()
                        .addGroup(paGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chPassword)
                            .addComponent(laPref)
                            .addComponent(laPath))
                        .addGap(14, 14, 14)
                        .addGroup(paGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPref, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addGroup(paGeneralLayout.createSequentialGroup()
                                .addComponent(tfPath, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbVersion, 0, 281, Short.MAX_VALUE)
                            .addComponent(tfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)))
                    .addComponent(laVersion))
                .addContainerGap())
        );
        paGeneralLayout.setVerticalGroup(
            paGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paGeneralLayout.createSequentialGroup()
                .addGroup(paGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laPref))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laVersion)
                    .addComponent(cbVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paSql.setBorder(javax.swing.BorderFactory.createTitledBorder("Работа с файлами"));

        chParseAll.setSelected(true);
        chParseAll.setText("Обрабатывать все файлы");
        chParseAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chParseAllActionPerformed(evt);
            }
        });

        chParseUsers.setSelected(true);
        chParseUsers.setText("Пользователи");
        chParseUsers.setEnabled(false);

        chParseForum.setSelected(true);
        chParseForum.setText("Форум");
        chParseForum.setEnabled(false);

        chParseLoads.setSelected(true);
        chParseLoads.setText("Каталог файлов");
        chParseLoads.setEnabled(false);

        chParsePubl.setSelected(true);
        chParsePubl.setText("Статьи");
        chParsePubl.setEnabled(false);

        chParseNews.setSelected(true);
        chParseNews.setText("Новости, блоги и FAQ");
        chParseNews.setEnabled(false);

        chParseComments.setSelected(true);
        chParseComments.setText("Комментарии");
        chParseComments.setEnabled(false);

        chEmpty.setSelected(true);
        chEmpty.setText("Очищать таблицы");

        chSplit.setText("Разбить SQL-скрипт на отдельные файлы");

        javax.swing.GroupLayout paSqlLayout = new javax.swing.GroupLayout(paSql);
        paSql.setLayout(paSqlLayout);
        paSqlLayout.setHorizontalGroup(
            paSqlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paSqlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paSqlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chParseAll)
                    .addGroup(paSqlLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(paSqlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chParseForum)
                            .addComponent(chParseUsers)
                            .addComponent(chParseLoads)
                            .addComponent(chParsePubl)
                            .addComponent(chParseNews)
                            .addComponent(chParseComments)))
                    .addComponent(chEmpty)
                    .addComponent(chSplit))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        paSqlLayout.setVerticalGroup(
            paSqlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paSqlLayout.createSequentialGroup()
                .addComponent(chParseAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chParseUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chParseForum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chParseLoads)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chParsePubl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chParseNews)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chParseComments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chEmpty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chSplit))
        );

        paParsing.setBorder(javax.swing.BorderFactory.createTitledBorder("Парсинг"));

        chWebAvatars.setText("Загрузка аватаров из Internet");

        chImage.setSelected(true);
        chImage.setText("Конвертация вложенных изображений на форуме ");

        chSmile.setText("Конвертация смайлов");

        chLinks.setSelected(true);
        chLinks.setText("Конвертация ссылок");
        chLinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chLinksActionPerformed(evt);
            }
        });

        laSiteOld.setText("Старое имя сайта");

        laSiteNew.setText("Новое имя сайта");

        laPost.setText("Число сообщений на странице форума");

        spPost.setModel(new javax.swing.SpinnerNumberModel(15, 1, 1000, 1));

        chFix.setSelected(true);
        chFix.setText("Разбор ошибочных тегов HTML");

        javax.swing.GroupLayout paParsingLayout = new javax.swing.GroupLayout(paParsing);
        paParsing.setLayout(paParsingLayout);
        paParsingLayout.setHorizontalGroup(
            paParsingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paParsingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paParsingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paParsingLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(paParsingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(laSiteOld)
                            .addComponent(laSiteNew)
                            .addComponent(laPost))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paParsingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSiteOld, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(tfSiteNew, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(spPost, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)))
                    .addComponent(chWebAvatars)
                    .addComponent(chImage)
                    .addComponent(chSmile)
                    .addComponent(chFix)
                    .addComponent(chLinks))
                .addContainerGap())
        );
        paParsingLayout.setVerticalGroup(
            paParsingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paParsingLayout.createSequentialGroup()
                .addComponent(chWebAvatars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chSmile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chFix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chLinks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paParsingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laSiteOld)
                    .addComponent(tfSiteOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paParsingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laSiteNew)
                    .addComponent(tfSiteNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paParsingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laPost)
                    .addComponent(spPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buStart.setText("Запустить конвертацию");
        buStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paGeneral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(paSql, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(paParsing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buStart, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paSql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paParsing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buStart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chPasswordActionPerformed
        tfPassword.setEnabled(chPassword.isSelected());
}//GEN-LAST:event_chPasswordActionPerformed

    private void chParseAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chParseAllActionPerformed
        if (chParseAll.isSelected()) {
            chParseUsers.setEnabled(false);
            chParseForum.setEnabled(false);
            chParseLoads.setEnabled(false);
            chParsePubl.setEnabled(false);
            chParseNews.setEnabled(false);
            chParseComments.setEnabled(false);
            chParseUsers.setSelected(true);
            chParseForum.setSelected(true);
            chParseLoads.setSelected(true);
            chParsePubl.setSelected(true);
            chParseNews.setSelected(true);
            chParseComments.setSelected(true);
        } else {
            chParseUsers.setEnabled(true);
            chParseForum.setEnabled(true);
            chParseLoads.setEnabled(true);
            chParsePubl.setEnabled(true);
            chParseNews.setEnabled(true);
            chParseComments.setEnabled(true);
        }
}//GEN-LAST:event_chParseAllActionPerformed

    private void chLinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chLinksActionPerformed
        laSiteOld.setEnabled(chLinks.isSelected());
        laSiteNew.setEnabled(chLinks.isSelected());
        laPost.setEnabled(chLinks.isSelected());
        tfSiteOld.setEnabled(chLinks.isSelected());
        tfSiteNew.setEnabled(chLinks.isSelected());
        spPost.setEnabled(chLinks.isSelected());
}//GEN-LAST:event_chLinksActionPerformed

    private void buPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buPathActionPerformed
        JFileChooser fcPath = new JFileChooser();
        fcPath.setDialogTitle("Путь к бекапу Ucoz");
        fcPath.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fcPath.setFileHidingEnabled(true);
        if (tfPath.getText() != null && !tfPath.getText().isEmpty()) {
            fcPath.setSelectedFile(new File(tfPath.getText()));
        }
        if (fcPath.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            tfPath.setText(fcPath.getSelectedFile().getAbsolutePath());
        }
}//GEN-LAST:event_buPathActionPerformed

    private void buStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buStartActionPerformed
        if (chPassword.isSelected() && tfPassword.getText().isEmpty()) {
            DMessage.ShowMessage("Ошибка", "Не задан пароль администратора.");
        } else if (chLinks.isSelected() && (tfSiteNew.getText().isEmpty() ||
                   tfSiteOld.getText().isEmpty())) {
            if (tfSiteOld.getText().isEmpty()) {
                DMessage.ShowMessage("Ошибка", "Не задано старое имя сайта.");
            } else if (tfSiteNew.getText().isEmpty()) {
                DMessage.ShowMessage("Ошибка", "Не задано новое имя сайта.");
            }
        } else {
            // Обработка данных
            DLog dLog = new DLog(this, true);
            dLog.setVisible(true);
        }
    }//GEN-LAST:event_buStartActionPerformed

    public void setPath (String path) {
        if (path != null) {
            String DS = File.separator;
            path = path.replace("\\", DS).replace("/", DS);
            tfPath.setText(path);
        } else {
            tfPath.setText(".");
        }
    }

    public void setPref (String pref) {
        if (pref != null) {
            tfPref.setText(pref);
        } else {
            tfPref.setText("");
        }
    }

    public void setPassword (String password) {
        if (password != null) {
            chPassword.setSelected(true);
            tfPassword.setText(password);
        } else {
            chPassword.setSelected(false);
            tfPassword.setText("");
        }
        chPasswordActionPerformed(null);
    }

    public void setSiteName (String site_old, String site_new, Integer postOnForum) {
        boolean en = false;
        if (site_old != null) {
            en = true;
            tfSiteOld.setText(site_old);
        } else {
            tfSiteOld.setText("");
        }
        if (site_new != null) {
            en = true;
            tfSiteNew.setText(site_new);
        } else {
            tfSiteNew.setText("");
        }
        if (postOnForum != null) {
            en = true;
            spPost.setValue(postOnForum);
        } else {
            spPost.setValue(15);
        }
        chLinks.setSelected(en);
        chLinksActionPerformed(null);
    }

    public void setParse (boolean parseAll, boolean[] parse) {
        chParseAll.setSelected(parseAll);
        chParseAllActionPerformed(null);
        if (!parseAll && parse.length >= 6) {
            chParseUsers.setSelected(parse[0]);
            chParseForum.setSelected(parse[1]);
            chParseLoads.setSelected(parse[2]);
            chParsePubl.setSelected(parse[3]);
            chParseNews.setSelected(parse[4]);
            chParseComments.setSelected(parse[5]);
        }
    }

    public void setNoEmpty (boolean noEmpty) {
        chEmpty.setSelected(!noEmpty);
    }

    public void setSplit (boolean sqlSplit) {
        chSplit.setSelected(sqlSplit);
    }

    public void setWebAvatars (boolean useWebAvatars) {
        chWebAvatars.setSelected(useWebAvatars);
    }

    public void setNoImage (boolean noImage) {
        chImage.setSelected(!noImage);
    }

    public void setSmile (boolean parseSmile) {
        chSmile.setSelected(parseSmile);
    }

    public void setNoFix (boolean noFix) {
        chFix.setSelected(!noFix);
    }

    public void setVersion (int version) {
        cbVersion.setSelectedIndex(version);
    }

    public String getPath () {
        String path = tfPath.getText();
        if (path != null) {
            String DS = File.separator;
            path = path.replace("\\", DS).replace("/", DS);
            if (path.length() > 0 && path.lastIndexOf(DS) == path.length()-1) {
                path = path.substring(0, path.length()-1);
            }
        }
        return path;
    }

    public String getPref () {
        return tfPref.getText();
    }

    public String getPassword () {
        if (chPassword.isSelected()) {
            return tfPassword.getText();
        } else {
            return null;
        }
    }

    public String getSiteNameOld () {
        if (chLinks.isSelected()) {
            String name = tfSiteOld.getText();
            if (name != null && name.toLowerCase().startsWith("http://")) {
                name = name.substring(7);
            }
            if (name != null && name.toLowerCase().startsWith("www.")) {
                name = name.substring(4);
            }
            return name;
        } else {
            return null;
        }
    }

    public String getSiteNameNew () {
        if (chLinks.isSelected()) {
            String name = tfSiteNew.getText();
            if (name != null && !name.toLowerCase().startsWith("http://") && !name.toLowerCase().startsWith("https://")) {
                name = "http://" + name;
            }
            return name;
        } else {
            return null;
        }
    }

    public Integer getPostOnForum () {
        if (chLinks.isSelected()) {
            return (Integer)spPost.getValue();
        } else {
            return null;
        }
    }

    public boolean getParseAll () {
        return chParseAll.isSelected();
    }

    public boolean[] getParse () {
        boolean[] parse = {chParseUsers.isSelected(),
                           chParseForum.isSelected(),
                           chParseLoads.isSelected(),
                           chParsePubl.isSelected(),
                           chParseNews.isSelected(),
                           chParseComments.isSelected()};
        return parse;
    }

    public boolean getEmpty () {
        return chEmpty.isSelected();
    }

    public boolean getSplit () {
        return chSplit.isSelected();
    }

    public boolean getWebAvatars () {
        return chWebAvatars.isSelected();
    }

    public boolean getImage () {
        return chImage.isSelected();
    }
    public boolean getSmile () {
        return chSmile.isSelected();
    }

    public boolean getFix () {
        return chFix.isSelected();
    }

    public int getVersion () {
        return cbVersion.getSelectedIndex();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buPath;
    private javax.swing.JButton buStart;
    private javax.swing.JComboBox cbVersion;
    private javax.swing.JCheckBox chEmpty;
    private javax.swing.JCheckBox chFix;
    private javax.swing.JCheckBox chImage;
    private javax.swing.JCheckBox chLinks;
    private javax.swing.JCheckBox chParseAll;
    private javax.swing.JCheckBox chParseComments;
    private javax.swing.JCheckBox chParseForum;
    private javax.swing.JCheckBox chParseLoads;
    private javax.swing.JCheckBox chParseNews;
    private javax.swing.JCheckBox chParsePubl;
    private javax.swing.JCheckBox chParseUsers;
    private javax.swing.JCheckBox chPassword;
    private javax.swing.JCheckBox chSmile;
    private javax.swing.JCheckBox chSplit;
    private javax.swing.JCheckBox chWebAvatars;
    private javax.swing.JLabel laPath;
    private javax.swing.JLabel laPost;
    private javax.swing.JLabel laPref;
    private javax.swing.JLabel laSiteNew;
    private javax.swing.JLabel laSiteOld;
    private javax.swing.JLabel laVersion;
    private javax.swing.JPanel paGeneral;
    private javax.swing.JPanel paParsing;
    private javax.swing.JPanel paSql;
    private javax.swing.JSpinner spPost;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfPath;
    private javax.swing.JTextField tfPref;
    private javax.swing.JTextField tfSiteNew;
    private javax.swing.JTextField tfSiteOld;
    // End of variables declaration//GEN-END:variables

}
